CREATE TABLE "achievements" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "achievements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"achievement_id" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"progress" integer DEFAULT 0 NOT NULL,
	"target" integer NOT NULL,
	"is_completed" boolean DEFAULT false NOT NULL,
	"reward" integer NOT NULL,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "audio_files" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audio_files_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"file_id" text NOT NULL,
	"blob_url" text NOT NULL,
	"file_type" text NOT NULL,
	"content_hash" text,
	"file_size" integer,
	"duration" integer,
	"format" text DEFAULT 'mp3' NOT NULL,
	"sample_rate" integer,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone,
	"access_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "audio_files_file_id_unique" UNIQUE("file_id")
);
--> statement-breakpoint
CREATE TABLE "badges" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "badges_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"badge_id" text NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"icon" text NOT NULL,
	"rarity" text NOT NULL,
	"earned_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cefr_progress" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cefr_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"current_level" text DEFAULT 'A1' NOT NULL,
	"target_level" text,
	"listening_progress" integer DEFAULT 0 NOT NULL,
	"speaking_progress" integer DEFAULT 0 NOT NULL,
	"reading_progress" integer DEFAULT 0 NOT NULL,
	"writing_progress" integer DEFAULT 0 NOT NULL,
	"total_points" integer DEFAULT 0 NOT NULL,
	"questions_completed" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cefr_progress_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "completed_questions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "completed_questions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"question_id" text NOT NULL,
	"user_answer" text,
	"correct_answer" text,
	"is_correct" boolean NOT NULL,
	"points_earned" integer DEFAULT 0 NOT NULL,
	"time_spent" integer,
	"skill" text NOT NULL,
	"difficulty" text,
	"answer_details" jsonb,
	"completed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "conversation_sessions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conversation_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"session_id" text NOT NULL,
	"scenario_id" text NOT NULL,
	"scenario_title" text NOT NULL,
	"target_turns" integer NOT NULL,
	"completed_turns" integer DEFAULT 0 NOT NULL,
	"total_points_earned" integer DEFAULT 0 NOT NULL,
	"average_pronunciation_score" numeric(5, 2),
	"average_fluency_score" numeric(5, 2),
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ended_at" timestamp with time zone,
	"is_completed" boolean DEFAULT false NOT NULL,
	CONSTRAINT "conversation_sessions_session_id_unique" UNIQUE("session_id")
);
--> statement-breakpoint
CREATE TABLE "conversation_turns" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conversation_turns_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"session_id" bigint NOT NULL,
	"turn_number" integer NOT NULL,
	"speaker" text NOT NULL,
	"audio_url" text,
	"audio_file_id" bigint,
	"transcription" text,
	"transcription_id" bigint,
	"ai_feedback" text,
	"pronunciation_score" numeric(5, 2),
	"fluency_score" numeric(5, 2),
	"grammar_score" numeric(5, 2),
	"vocabulary_score" numeric(5, 2),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "copilot_conversations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "copilot_conversations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"session_id" text NOT NULL,
	"context_type" text NOT NULL,
	"context_id" text,
	"title" text,
	"message_count" integer DEFAULT 0 NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_message_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "copilot_conversations_session_id_unique" UNIQUE("session_id")
);
--> statement-breakpoint
CREATE TABLE "copilot_messages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "copilot_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"conversation_id" bigint NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"content_type" text DEFAULT 'text' NOT NULL,
	"metadata" jsonb,
	"audio_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "module_progress" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "module_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"module_type" text NOT NULL,
	"total_time" integer DEFAULT 0 NOT NULL,
	"questions_completed" integer DEFAULT 0 NOT NULL,
	"points_earned" integer DEFAULT 0 NOT NULL,
	"last_accessed" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "practice_sessions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "practice_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"session_id" text NOT NULL,
	"skill" text NOT NULL,
	"level" text NOT NULL,
	"questions_attempted" integer DEFAULT 0 NOT NULL,
	"questions_correct" integer DEFAULT 0 NOT NULL,
	"total_points_earned" integer DEFAULT 0 NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ended_at" timestamp with time zone,
	"duration" integer,
	"is_completed" boolean DEFAULT false NOT NULL,
	CONSTRAINT "practice_sessions_session_id_unique" UNIQUE("session_id")
);
--> statement-breakpoint
CREATE TABLE "question_audio_cache" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "question_audio_cache_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"question_id" text NOT NULL,
	"audio_file_id" bigint,
	"text_content" text NOT NULL,
	"voice_model" text NOT NULL,
	"voice_name" text NOT NULL,
	"language" text DEFAULT 'en' NOT NULL,
	"content_hash" text NOT NULL,
	"generated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_accessed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"access_count" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "question_audio_cache_question_id_unique" UNIQUE("question_id")
);
--> statement-breakpoint
CREATE TABLE "session_answers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_answers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"session_id" bigint NOT NULL,
	"question_id" text NOT NULL,
	"user_answer" text,
	"correct_answer" text,
	"is_correct" boolean NOT NULL,
	"points_earned" integer DEFAULT 0 NOT NULL,
	"time_spent" integer,
	"audio_recording_id" bigint,
	"transcription_id" bigint,
	"ai_feedback" text,
	"answered_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "transcriptions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "transcriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"audio_file_id" bigint,
	"user_id" text NOT NULL,
	"transcribed_text" text NOT NULL,
	"language" text,
	"confidence" numeric(5, 4),
	"model" text NOT NULL,
	"word_count" integer,
	"processing_time" integer,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_progress" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"current_level" text DEFAULT 'foundation' NOT NULL,
	"target_level" text,
	"listening_progress" integer DEFAULT 0 NOT NULL,
	"speaking_progress" integer DEFAULT 0 NOT NULL,
	"reading_progress" integer DEFAULT 0 NOT NULL,
	"writing_progress" integer DEFAULT 0 NOT NULL,
	"total_points" integer DEFAULT 0 NOT NULL,
	"questions_completed" integer DEFAULT 0 NOT NULL,
	"correct_answers" integer DEFAULT 0 NOT NULL,
	"streak" integer DEFAULT 0 NOT NULL,
	"perfect_streak" integer DEFAULT 0 NOT NULL,
	"last_study_date" timestamp with time zone,
	"total_study_time" integer DEFAULT 0 NOT NULL,
	"preferred_voice" text DEFAULT 'alloy',
	"audio_playback_speed" numeric(3, 2) DEFAULT '1.00',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_progress_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "user_recordings" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_recordings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"audio_file_id" bigint,
	"recording_type" text NOT NULL,
	"context_id" text,
	"question_id" text,
	"transcription_id" bigint,
	"duration" integer,
	"recorded_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "achievements_user_id_idx" ON "achievements" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "achievements_achievement_id_idx" ON "achievements" USING btree ("achievement_id");--> statement-breakpoint
CREATE INDEX "audio_files_file_id_idx" ON "audio_files" USING btree ("file_id");--> statement-breakpoint
CREATE INDEX "audio_files_content_hash_idx" ON "audio_files" USING btree ("content_hash");--> statement-breakpoint
CREATE INDEX "audio_files_file_type_idx" ON "audio_files" USING btree ("file_type");--> statement-breakpoint
CREATE INDEX "badges_user_id_idx" ON "badges" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "cefr_progress_user_id_idx" ON "cefr_progress" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "completed_questions_user_id_idx" ON "completed_questions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "completed_questions_question_id_idx" ON "completed_questions" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "completed_questions_skill_idx" ON "completed_questions" USING btree ("skill");--> statement-breakpoint
CREATE INDEX "conversation_sessions_user_id_idx" ON "conversation_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "conversation_sessions_session_id_idx" ON "conversation_sessions" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "conversation_turns_session_id_idx" ON "conversation_turns" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "conversation_turns_turn_number_idx" ON "conversation_turns" USING btree ("turn_number");--> statement-breakpoint
CREATE INDEX "copilot_conversations_user_id_idx" ON "copilot_conversations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "copilot_conversations_context_idx" ON "copilot_conversations" USING btree ("context_type","context_id");--> statement-breakpoint
CREATE INDEX "copilot_conversations_session_id_idx" ON "copilot_conversations" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "copilot_messages_conversation_id_idx" ON "copilot_messages" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "copilot_messages_created_at_idx" ON "copilot_messages" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "module_progress_user_id_module_idx" ON "module_progress" USING btree ("user_id","module_type");--> statement-breakpoint
CREATE INDEX "practice_sessions_user_id_idx" ON "practice_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "practice_sessions_started_at_idx" ON "practice_sessions" USING btree ("started_at");--> statement-breakpoint
CREATE INDEX "practice_sessions_session_id_idx" ON "practice_sessions" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "question_audio_cache_question_id_idx" ON "question_audio_cache" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "question_audio_cache_content_hash_idx" ON "question_audio_cache" USING btree ("content_hash");--> statement-breakpoint
CREATE INDEX "session_answers_session_id_idx" ON "session_answers" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "session_answers_question_id_idx" ON "session_answers" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "transcriptions_audio_file_id_idx" ON "transcriptions" USING btree ("audio_file_id");--> statement-breakpoint
CREATE INDEX "transcriptions_user_id_idx" ON "transcriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_progress_user_id_idx" ON "user_progress" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_recordings_user_id_idx" ON "user_recordings" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_recordings_context_id_idx" ON "user_recordings" USING btree ("context_id");--> statement-breakpoint
CREATE INDEX "user_recordings_audio_file_id_idx" ON "user_recordings" USING btree ("audio_file_id");