CREATE TABLE "assignment_student_status" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assignment_student_status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"assignment_id" bigint NOT NULL,
	"student_id" bigint NOT NULL,
	"status" text DEFAULT 'assigned' NOT NULL,
	"assigned_at" timestamp with time zone DEFAULT now() NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"progress_percentage" integer DEFAULT 0 NOT NULL,
	"time_spent" integer DEFAULT 0 NOT NULL,
	"teacher_viewed" boolean DEFAULT false NOT NULL,
	"teacher_feedback" text,
	"teacher_score" integer,
	"feedback_given_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "assignment_submissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assignment_submissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"assignment_id" bigint NOT NULL,
	"student_id" bigint NOT NULL,
	"student_status_id" bigint NOT NULL,
	"submission_type" text NOT NULL,
	"practice_session_id" bigint,
	"diagnostic_attempt_id" bigint,
	"content" jsonb,
	"audio_recording_ids" bigint[],
	"transcription_ids" bigint[],
	"questions_completed" integer DEFAULT 0 NOT NULL,
	"questions_correct" integer,
	"total_points_earned" integer DEFAULT 0 NOT NULL,
	"ai_assessment" jsonb,
	"submitted_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "assignment_targets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assignment_targets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"assignment_id" bigint NOT NULL,
	"target_type" text NOT NULL,
	"target_id" bigint NOT NULL,
	"assigned_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "assignments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assignments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"created_by_teacher_id" bigint NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"instructions" text,
	"assignment_type" text NOT NULL,
	"target_skill" text,
	"target_level" text,
	"requirements" jsonb,
	"due_date" timestamp with time zone,
	"is_recurring" boolean DEFAULT false NOT NULL,
	"recurring_pattern" jsonb,
	"points_reward" integer,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "class_analytics" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "class_analytics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"class_id" bigint NOT NULL,
	"date" timestamp with time zone NOT NULL,
	"total_students" integer NOT NULL,
	"active_students" integer NOT NULL,
	"avg_listening_progress" numeric(5, 2),
	"avg_speaking_progress" numeric(5, 2),
	"avg_reading_progress" numeric(5, 2),
	"avg_writing_progress" numeric(5, 2),
	"total_time_spent" integer DEFAULT 0 NOT NULL,
	"total_questions_completed" integer DEFAULT 0 NOT NULL,
	"average_accuracy" numeric(5, 2),
	"top_performers" bigint[],
	"needs_attention" bigint[],
	"generated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "class_enrollments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "class_enrollments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"class_id" bigint NOT NULL,
	"student_id" bigint NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"enrolled_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "class_teachers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "class_teachers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"class_id" bigint NOT NULL,
	"teacher_id" bigint NOT NULL,
	"role" text NOT NULL,
	"assigned_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "classes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "classes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"department_id" bigint,
	"grade_level_id" bigint,
	"name" text NOT NULL,
	"teacher_id" bigint NOT NULL,
	"academic_year" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "departments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "departments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"head_teacher_id" bigint,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "diagnostic_question_responses" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "diagnostic_question_responses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"attempt_id" bigint NOT NULL,
	"question_id" bigint NOT NULL,
	"student_answer" text,
	"audio_recording_id" bigint,
	"transcription_id" bigint,
	"is_correct" boolean,
	"points_earned" integer DEFAULT 0 NOT NULL,
	"ai_assessment" jsonb,
	"time_spent" integer,
	"answered_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "diagnostic_test_questions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "diagnostic_test_questions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"test_section_id" bigint NOT NULL,
	"question_type" text NOT NULL,
	"question_text" text NOT NULL,
	"options" jsonb,
	"correct_answer" text,
	"difficulty_level" text NOT NULL,
	"points" integer DEFAULT 1 NOT NULL,
	"rubric" jsonb,
	"audio_url" text,
	"image_url" text,
	"order_index" integer NOT NULL,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "diagnostic_test_sections" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "diagnostic_test_sections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"diagnostic_test_id" bigint NOT NULL,
	"skill_type" text NOT NULL,
	"section_name" text NOT NULL,
	"level_range_min" text NOT NULL,
	"level_range_max" text NOT NULL,
	"total_questions" integer NOT NULL,
	"passing_threshold" numeric(3, 2),
	"order_index" integer NOT NULL,
	"instructions" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "diagnostic_tests" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "diagnostic_tests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint,
	"name" text NOT NULL,
	"description" text,
	"level_system" text NOT NULL,
	"test_type" text NOT NULL,
	"target_skills" text[],
	"estimated_duration" integer,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_system_test" boolean DEFAULT false NOT NULL,
	"created_by_user_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "grade_levels" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "grade_levels_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"name" text NOT NULL,
	"order_index" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organization_question_access" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organization_question_access_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"question_bank_id" bigint NOT NULL,
	"access_type" text NOT NULL,
	"granted_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organizations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organizations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"settings" jsonb,
	"subscription_tier" text DEFAULT 'basic' NOT NULL,
	"max_students" integer,
	"is_active" boolean DEFAULT true NOT NULL,
	"contact_email" text,
	"contact_phone" text,
	"address" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "organizations_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "parent_student_relationships" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "parent_student_relationships_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"parent_id" bigint NOT NULL,
	"student_id" bigint NOT NULL,
	"relationship_type" text NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "question_bank_questions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "question_bank_questions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"question_bank_id" bigint NOT NULL,
	"question_id" text NOT NULL,
	"question_data" jsonb NOT NULL,
	"skill_type" text NOT NULL,
	"difficulty_level" text NOT NULL,
	"tags" text[],
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "question_banks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "question_banks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint,
	"name" text NOT NULL,
	"description" text,
	"level_system" text NOT NULL,
	"is_system_bank" boolean DEFAULT false NOT NULL,
	"is_public" boolean DEFAULT false NOT NULL,
	"created_by_user_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "role_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"role" text NOT NULL,
	"resource" text NOT NULL,
	"action" text NOT NULL,
	"scope" text NOT NULL,
	"conditions" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "student_diagnostic_attempts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_diagnostic_attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"student_id" bigint NOT NULL,
	"organization_id" bigint NOT NULL,
	"diagnostic_test_id" bigint NOT NULL,
	"attempt_number" integer DEFAULT 1 NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"is_completed" boolean DEFAULT false NOT NULL,
	"total_duration" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "student_diagnostic_results" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_diagnostic_results_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"student_id" bigint NOT NULL,
	"organization_id" bigint NOT NULL,
	"attempt_id" bigint NOT NULL,
	"diagnostic_test_id" bigint NOT NULL,
	"level_system" text NOT NULL,
	"overall_level" text NOT NULL,
	"skill_levels" jsonb NOT NULL,
	"skill_scores" jsonb NOT NULL,
	"strengths" text[],
	"areas_for_improvement" text[],
	"recommended_next_steps" text[],
	"total_score" integer NOT NULL,
	"percentage_score" numeric(5, 2) NOT NULL,
	"reviewed_by_teacher_id" bigint,
	"teacher_comments" text,
	"reviewed_at" timestamp with time zone,
	"completed_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "student_group_members" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_group_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"student_group_id" bigint NOT NULL,
	"student_id" bigint NOT NULL,
	"added_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "student_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"created_by_teacher_id" bigint NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "teacher_insights" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "teacher_insights_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"teacher_id" bigint NOT NULL,
	"insight_type" text NOT NULL,
	"scope_type" text NOT NULL,
	"scope_id" bigint NOT NULL,
	"time_period_start" timestamp with time zone,
	"time_period_end" timestamp with time zone,
	"data" jsonb NOT NULL,
	"generated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"acknowledged_at" timestamp with time zone,
	"is_dismissed" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"organization_id" bigint NOT NULL,
	"permission_type" text NOT NULL,
	"resource" text NOT NULL,
	"action" text NOT NULL,
	"granted_by_user_id" bigint NOT NULL,
	"granted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"stack_user_id" text NOT NULL,
	"email" text NOT NULL,
	"full_name" text NOT NULL,
	"role" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_stack_user_id_unique" UNIQUE("stack_user_id")
);
--> statement-breakpoint
ALTER TABLE "achievements" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "audio_files" ADD COLUMN "organization_id" bigint;--> statement-breakpoint
ALTER TABLE "badges" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "cefr_progress" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "completed_questions" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "conversation_sessions" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "conversation_turns" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "copilot_conversations" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "copilot_messages" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "module_progress" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "practice_sessions" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "question_audio_cache" ADD COLUMN "organization_id" bigint;--> statement-breakpoint
ALTER TABLE "session_answers" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "transcriptions" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "user_progress" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "user_recordings" ADD COLUMN "organization_id" bigint NOT NULL;--> statement-breakpoint
CREATE INDEX "assignment_student_status_assignment_id_idx" ON "assignment_student_status" USING btree ("assignment_id");--> statement-breakpoint
CREATE INDEX "assignment_student_status_student_id_idx" ON "assignment_student_status" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "assignment_student_status_status_idx" ON "assignment_student_status" USING btree ("status");--> statement-breakpoint
CREATE INDEX "assignment_submissions_assignment_id_idx" ON "assignment_submissions" USING btree ("assignment_id");--> statement-breakpoint
CREATE INDEX "assignment_submissions_student_id_idx" ON "assignment_submissions" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "assignment_submissions_submission_type_idx" ON "assignment_submissions" USING btree ("submission_type");--> statement-breakpoint
CREATE INDEX "assignment_targets_assignment_id_idx" ON "assignment_targets" USING btree ("assignment_id");--> statement-breakpoint
CREATE INDEX "assignment_targets_target_type_idx" ON "assignment_targets" USING btree ("target_type");--> statement-breakpoint
CREATE INDEX "assignment_targets_target_id_idx" ON "assignment_targets" USING btree ("target_id");--> statement-breakpoint
CREATE INDEX "assignments_organization_id_idx" ON "assignments" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "assignments_created_by_teacher_id_idx" ON "assignments" USING btree ("created_by_teacher_id");--> statement-breakpoint
CREATE INDEX "assignments_status_idx" ON "assignments" USING btree ("status");--> statement-breakpoint
CREATE INDEX "assignments_due_date_idx" ON "assignments" USING btree ("due_date");--> statement-breakpoint
CREATE INDEX "class_analytics_class_id_idx" ON "class_analytics" USING btree ("class_id");--> statement-breakpoint
CREATE INDEX "class_analytics_date_idx" ON "class_analytics" USING btree ("date");--> statement-breakpoint
CREATE INDEX "class_enrollments_class_id_idx" ON "class_enrollments" USING btree ("class_id");--> statement-breakpoint
CREATE INDEX "class_enrollments_student_id_idx" ON "class_enrollments" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "class_enrollments_status_idx" ON "class_enrollments" USING btree ("status");--> statement-breakpoint
CREATE INDEX "class_teachers_class_id_idx" ON "class_teachers" USING btree ("class_id");--> statement-breakpoint
CREATE INDEX "class_teachers_teacher_id_idx" ON "class_teachers" USING btree ("teacher_id");--> statement-breakpoint
CREATE INDEX "classes_organization_id_idx" ON "classes" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "classes_teacher_id_idx" ON "classes" USING btree ("teacher_id");--> statement-breakpoint
CREATE INDEX "classes_grade_level_id_idx" ON "classes" USING btree ("grade_level_id");--> statement-breakpoint
CREATE INDEX "classes_department_id_idx" ON "classes" USING btree ("department_id");--> statement-breakpoint
CREATE INDEX "departments_organization_id_idx" ON "departments" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "departments_head_teacher_id_idx" ON "departments" USING btree ("head_teacher_id");--> statement-breakpoint
CREATE INDEX "diagnostic_question_responses_attempt_id_idx" ON "diagnostic_question_responses" USING btree ("attempt_id");--> statement-breakpoint
CREATE INDEX "diagnostic_question_responses_question_id_idx" ON "diagnostic_question_responses" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "diagnostic_test_questions_section_id_idx" ON "diagnostic_test_questions" USING btree ("test_section_id");--> statement-breakpoint
CREATE INDEX "diagnostic_test_questions_order_idx" ON "diagnostic_test_questions" USING btree ("order_index");--> statement-breakpoint
CREATE INDEX "diagnostic_test_sections_test_id_idx" ON "diagnostic_test_sections" USING btree ("diagnostic_test_id");--> statement-breakpoint
CREATE INDEX "diagnostic_test_sections_order_idx" ON "diagnostic_test_sections" USING btree ("order_index");--> statement-breakpoint
CREATE INDEX "diagnostic_tests_organization_id_idx" ON "diagnostic_tests" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "diagnostic_tests_level_system_idx" ON "diagnostic_tests" USING btree ("level_system");--> statement-breakpoint
CREATE INDEX "diagnostic_tests_is_active_idx" ON "diagnostic_tests" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "grade_levels_organization_id_idx" ON "grade_levels" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "grade_levels_order_idx" ON "grade_levels" USING btree ("order_index");--> statement-breakpoint
CREATE INDEX "organization_question_access_organization_id_idx" ON "organization_question_access" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "organization_question_access_question_bank_id_idx" ON "organization_question_access" USING btree ("question_bank_id");--> statement-breakpoint
CREATE INDEX "organizations_slug_idx" ON "organizations" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "organizations_is_active_idx" ON "organizations" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "parent_student_relationships_parent_id_idx" ON "parent_student_relationships" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "parent_student_relationships_student_id_idx" ON "parent_student_relationships" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "question_bank_questions_bank_id_idx" ON "question_bank_questions" USING btree ("question_bank_id");--> statement-breakpoint
CREATE INDEX "question_bank_questions_question_id_idx" ON "question_bank_questions" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "question_bank_questions_skill_type_idx" ON "question_bank_questions" USING btree ("skill_type");--> statement-breakpoint
CREATE INDEX "question_bank_questions_difficulty_level_idx" ON "question_bank_questions" USING btree ("difficulty_level");--> statement-breakpoint
CREATE INDEX "question_banks_organization_id_idx" ON "question_banks" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "question_banks_is_system_bank_idx" ON "question_banks" USING btree ("is_system_bank");--> statement-breakpoint
CREATE INDEX "role_permissions_role_idx" ON "role_permissions" USING btree ("role");--> statement-breakpoint
CREATE INDEX "role_permissions_resource_idx" ON "role_permissions" USING btree ("resource");--> statement-breakpoint
CREATE INDEX "role_permissions_action_idx" ON "role_permissions" USING btree ("action");--> statement-breakpoint
CREATE INDEX "student_diagnostic_attempts_student_id_idx" ON "student_diagnostic_attempts" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "student_diagnostic_attempts_test_id_idx" ON "student_diagnostic_attempts" USING btree ("diagnostic_test_id");--> statement-breakpoint
CREATE INDEX "student_diagnostic_attempts_is_completed_idx" ON "student_diagnostic_attempts" USING btree ("is_completed");--> statement-breakpoint
CREATE INDEX "student_diagnostic_results_student_id_idx" ON "student_diagnostic_results" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "student_diagnostic_results_organization_id_idx" ON "student_diagnostic_results" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "student_diagnostic_results_level_system_idx" ON "student_diagnostic_results" USING btree ("level_system");--> statement-breakpoint
CREATE INDEX "student_diagnostic_results_completed_at_idx" ON "student_diagnostic_results" USING btree ("completed_at");--> statement-breakpoint
CREATE INDEX "student_group_members_group_id_idx" ON "student_group_members" USING btree ("student_group_id");--> statement-breakpoint
CREATE INDEX "student_group_members_student_id_idx" ON "student_group_members" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "student_groups_organization_id_idx" ON "student_groups" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "student_groups_created_by_teacher_id_idx" ON "student_groups" USING btree ("created_by_teacher_id");--> statement-breakpoint
CREATE INDEX "teacher_insights_organization_id_idx" ON "teacher_insights" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "teacher_insights_teacher_id_idx" ON "teacher_insights" USING btree ("teacher_id");--> statement-breakpoint
CREATE INDEX "teacher_insights_insight_type_idx" ON "teacher_insights" USING btree ("insight_type");--> statement-breakpoint
CREATE INDEX "teacher_insights_scope_type_idx" ON "teacher_insights" USING btree ("scope_type");--> statement-breakpoint
CREATE INDEX "teacher_insights_scope_id_idx" ON "teacher_insights" USING btree ("scope_id");--> statement-breakpoint
CREATE INDEX "user_permissions_user_id_idx" ON "user_permissions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_permissions_organization_id_idx" ON "user_permissions" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "users_organization_id_idx" ON "users" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "users_stack_user_id_idx" ON "users" USING btree ("stack_user_id");--> statement-breakpoint
CREATE INDEX "users_role_idx" ON "users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "users_email_idx" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "achievements_organization_id_idx" ON "achievements" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "audio_files_organization_id_idx" ON "audio_files" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "badges_organization_id_idx" ON "badges" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "cefr_progress_organization_id_idx" ON "cefr_progress" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "completed_questions_organization_id_idx" ON "completed_questions" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "conversation_sessions_organization_id_idx" ON "conversation_sessions" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "conversation_turns_organization_id_idx" ON "conversation_turns" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "copilot_conversations_organization_id_idx" ON "copilot_conversations" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "copilot_messages_organization_id_idx" ON "copilot_messages" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "module_progress_organization_id_idx" ON "module_progress" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "practice_sessions_organization_id_idx" ON "practice_sessions" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "question_audio_cache_organization_id_idx" ON "question_audio_cache" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "session_answers_organization_id_idx" ON "session_answers" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "transcriptions_organization_id_idx" ON "transcriptions" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "user_progress_organization_id_idx" ON "user_progress" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "user_recordings_organization_id_idx" ON "user_recordings" USING btree ("organization_id");